### ISSUE TITLE
Make style importing optional

### ISSUE THREAD

**Issue by scottmessinger** [abedonik/ember-tags-input#4]
I love the addon! I couldn't figure out a way to optionally import the styles, so I just copied and pasted the component into my app. I would love to go back to using the addon and just styling it in my app. Thanks for your great work on this!

**Comment by abedonik** [comment]
@scottmessinger Hello, thank you for issue! I will add this functionality soon.

**Comment by abedonik** [comment]
@scottmessinger Hello! I've released a new version of addon which has changes for optional using default styles. see https://github.com/abedonik/ember-tags-input#installation
